[package]
name = "iriv-io-modbus-tcp"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
keywords = ["cytron", "iriv-io", "iot", "modbus", "remote-io"]
categories = ["hardware-support"]
description = "Modbus/TCP firmware for the Cytron IRIV IO."
readme = "README.md"
repository = "https://github.com/andergisomon/iriv-io-modbus-tcp"

[[example]]
name = "example"
path = "usage_example/example.rs"

[dependencies]
embassy-executor = "0.9.1"
embassy-futures = "0.1.2"
embassy-net = "0.7.1"
embassy-rp = "0.8.0"
embedded-hal-bus = "0.3.0"
modbus-core = { version = "0.2.0", default-featues = false, features = ["tcp"]}
static_cell = "2.1.1"
